#!/usr/bin/env python3

from sys import argv, exit as exit_code
from os import system, path

def GREEN(text):
    return("\033[32m%s\033[0m" % str(text))

def main():
    if len(argv) < 3:
        print('Usage: %s [attacker ip] [local port to bind on]' % (argv[0]))
        exit_code(-1)
    ipaddr, port = argv[1], argv[2]
    shells = path.join(path.dirname(path.realpath(__file__)), 'shells.txt')
    for shell in open(shells):
        try:
            desc, cmd = shell.split('|', 1)
            cmd = cmd.replace("[IPADDR]", ipaddr)
            cmd = cmd.replace("[PORT]", port)
            print(GREEN(desc))
            print(cmd)
        except:
            None

if __name__ == "__main__":
    main()
